import os
from enum import Enum


class Config(str, Enum):
    RABBITMQ_USERNAME = "RABBITMQ_USERNAME"
    RABBITMQ_PASSWORD = "RABBITMQ_PASSWORD"
    RABBITMQ_HOST = "RABBITMQ_HOST"
    RABBITMQ_QUEUE = "RABBITMQ_QUEUE"
    RABBITMQ_ROUTING_KEY = "RABBITMQ_ROUTING_KEY"
    RABBITMQ_EXCHANGE = "RABBITMQ_EXCHANGE"
    SERVER_PORT = "SERVER_PORT"
    SERVER_HOST = "SERVER_HOST"
    POSTGRES_USER = "POSTGRES_USER"
    POSTGRES_PASSWORD = "POSTGRES_PASSWORD"
    POSTGRES_HOST = "POSTGRES_HOST"
    DATABASE_URL = "DATABASE_URL"
    PRODUCER_DB_NAME = "PRODUCER_DB_NAME"
    RECEIVER_DB_NAME = "RECEIVER_DB_NAME"

    def get_env(self, variable=None):
        return os.environ.get(self, variable)
